apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-devsecops-app
  labels:
    app: enterprise-devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise-devsecops-app
  template:
    metadata:
      labels:
        app: enterprise-devsecops-app
    spec:
      containers:
      - name: enterprise-devsecops-app
        image: ghcr.io/mohak007/enterprise-devsecops-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
